language: go 

go: 
    - 1.12.x

sudo: true

before_install: 
    - go get -u golang.org/x/lint/golint
    - go get github.com/securego/gosec/cmd/gosec/...
    - go get golang.org/x/tools/cmd/goimports
    - go get github.com/stretchr/testify

script:
    - go fmt ./...
    - golint ./...
    - gosec ./...
    - goimports ./

    - go test ./...

    - go build main.go

    # docker image check

    # docker image push to dockerhub check

    # github checks

    