language: go

go:
    - 1.12.x

services:
    - docker

sudo: true

jobs:
    include:
        - stage: check
          install:
          - go get -u golang.org/x/lint/golint
          - go get github.com/securego/gosec/cmd/gosec/...
          - go get golang.org/x/tools/cmd/goimports
          script:
          - gofmt -d ./
          - bash build/gofmt_check.sh

          - golint ./...

          - gosec ./...

          - goimports -d ./
          - bash build/goimports_check.sh

        - stage: test
          script:
          - go test -race -coverprofile=coverage.out -covermode=atomic ./...

          after_success:
          - bash <(curl -s https://codecov.io/bash)


        - stage: build
          script:
          - go build cmd/web-app/main.go

          - docker build -f docker/web-app/Dockerfile -t $WEB_TAG:$TRAVIS_TAG .

          after_success:
          - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin

          - docker tag $WEB_TAG:$TRAVIS_TAG $DOCKER_LOGIN/$WEB_TAG:$TRAVIS_TAG

          - docker push $DOCKER_LOGIN/$WEB_TAG:$TRAVIS_TAG

stages:
    - checks
    - test
    - name: build
      if: tag ~= /\d(.\d)+/