language: go 

go: 
    - 1.12.x

services: 
    - docker

sudo: true

before_install: 
    - go get -u golang.org/x/lint/golint
    - go get github.com/securego/gosec/cmd/gosec/...
    - go get golang.org/x/tools/cmd/goimports
    - go get -u github.com/golang/dep/cmd/dep
    - dep init
    - dep ensure

script:
    - gofmt -d ./
    - bash build/gofmt_check.sh

    - golint ./...

    - gosec ./...

    - goimports -d ./
    - bash build/goimports_check.sh

    - go test -race -coverprofile=coverage.out -covermode=atomic ./...

    - go build cmd/web-app/main.go

    - sudo docker build -f docker/web-app/Dockerfile -t "github-aggregator-web" . 

    # docker image check

    # docker image push to dockerhub check

    # github checks

after_success:
    - bash <(curl -s https://codecov.io/bash) 

    