language: go

go:
    - 1.12.x

services:
    - docker

sudo: true

jobs:
    include:
        - stage: check
          install:
          - go get -u golang.org/x/lint/golint
          - go get github.com/securego/gosec/cmd/gosec/...
          - go get golang.org/x/tools/cmd/goimports
          script:
          - gofmt -d $(find . -type f -name '*.go' -not -path "./vendor/*")
          - bash build/gofmt_check.sh

          - go list ./... | grep -v /vendor/ | xargs -n 1 golint

          - gosec $(find . -type f -name '*.go' -not -path "./vendor/*")

          - goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*")
          - bash build/goimports_check.sh

        - stage: test
          script:
          - go test -race -coverprofile=coverage.out -covermode=atomic ./...

          after_success:
          - bash <(curl -s https://codecov.io/bash)

        - stage: build
          script:
          - go build cmd/web-app/main.go

          deploy:
            provider: script
            script: bash build/docker_push.sh

stages:
    - checks
    - test
    - name: build
      if: type = pull_request || tag ~= /\d(.\d)+/