language: go 

go: 
    - 1.12.x

sudo: true

before_install: 
    - go get -u golang.org/x/lint/golint
    - go get github.com/securego/gosec/cmd/gosec/...
    - go get golang.org/x/tools/cmd/goimports
    - go get -u github.com/golang/dep/cmd/dep
    - dep init
    - dep ensure

script:
    - gofmt -d ./
    - bash build/gofmt_check.sh
    - golint ./...
    - gosec ./...
    - goimports -d ./
    - bash build/goimports_check.sh

    - go test ./...

    - go build cmd/web-app/main.go

    # docker image check

    # docker image push to dockerhub check

    # github checks

    