codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...75"
  status:
    project:
      default:
        target: 50%
        treshtold: null
    patch:
      default:
        enabled: no
    changes:
      default:
        enabled: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
