[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.1"
